M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu24.04.1} date 2026-03-07T17:58:06-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-07T17:58:06-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X103.5Y-73.5
X103.5Y-96.5
X161.5Y-73.5
X161.5Y-96.5
M30
