M48
; DRILL file {KiCad 9.0.9-9.0.9~ubuntu24.04.1} date 2026-06-15T11:45:31-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-15T11:45:31-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9-9.0.9~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X103.5Y-73.5
X103.5Y-96.5
X161.5Y-73.5
X161.5Y-96.5
M30
